name: HappyHotel
main: com.github.nunetnetworks.HappyHotel.HappyHotel
version: 0.1beta
permissions:
    happyhotel.*:
        description: give access to all blocks
        children:
            happyhotel.info: true
    happyhotel.info:
        default: false
commands:
    hh-info:
        description: Get all HappyHotel info
        usage: "Usage : /<command>"
        permission: happyhotel.info
        permission-message: You don't have permission <permission>